# Generated by Django 3.2 on 2023-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20230612_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (3, '3'), (5, '5'), (0, '0')]),
        ),
    ]
