# Generated by Django 3.2 on 2023-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20230613_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(5, '5'), (0, '0'), (2, '2'), (4, '4'), (3, '3'), (1, '1')]),
        ),
    ]
