# Generated by Django 3.2 on 2023-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (4, '4'), (0, '0'), (5, '5'), (2, '2')]),
        ),
    ]
